import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.buyers': 'Buyers',
    'nav.sellers': 'Sellers',
    'nav.browseAuctions': 'Browse Auctions',
    'nav.auctions': 'Auctions',
    'nav.contact': 'Contact',
    'hero.title': 'CROWN AUCTIONS',
    'hero.subtitle': 'Surplus Retail Stock & Vendor Liquidations from numerous licensed dealers',
    'hero.cta': 'Get Started Today',
    'hero.howItWorks': 'How it Works',
    'hero.step1.title': 'TELL US ABOUT YOUR ITEMS',
    'hero.step1.desc': 'Include photos and any relevant documents or certificates. Detailed information will improve our level of service.',
    'hero.step2.title': 'SCHEDULE A VISIT',
    'hero.step2.desc': 'Select a date and time to meet privately with our expert. Receive a free evaluation of your items with no obligation to sell.',
    'hero.step3.title': 'MEET WITH AN EXPERT TO RECEIVE AN OFFER',
    'hero.step3.desc': 'Upon review of your items, we\'ll provide a purchase offer. There are no fees or commissions for our service.',
    'hero.step4.title': 'GET PAID',
    'hero.step4.desc': 'Receive immediate payment by bank transfer.',
    'itemCategory.title': 'What kind of item do you have?',
    'itemCategory.subtitle': 'Select the category that best describes your item',
    'itemCategory.diamonds': 'Diamonds',
    'itemCategory.diamondsDesc': 'Loose diamonds & certified stones',
    'itemCategory.watches': 'Watches',
    'itemCategory.watchesDesc': 'Luxury & Swiss timepieces',
    'itemCategory.jewelry': 'Jewelry',
    'itemCategory.jewelryDesc': 'Necklaces, bracelets & earrings',
    'itemCategory.rings': 'Rings',
    'itemCategory.ringsDesc': 'Engagement & wedding rings',
    'itemCategory.luxury': 'Luxury Items',
    'itemCategory.luxuryDesc': 'Designer & collectible pieces',
    'itemCategory.other': 'Other',
    'itemCategory.otherDesc': 'Other valuable items',
    'itemCategory.hint': 'Our experts will help you determine the best category for your item',
    'about.title': 'About Crown Auctions',
    'about.description': 'Crown Auctions is a premier luxury auction house specializing in fine jewelry, diamonds, and Swiss watches. With decades of expertise, we connect discerning buyers with exceptional pieces.',
    'about.history.title': 'Our History',
    'about.history.content': 'Founded in 1985, Crown Auctions began as a small family-owned jewelry business in Sydney. Over nearly four decades, we have grown into one of the most respected auction houses in the Asia-Pacific region. Our founders passion for exquisite timepieces and fine jewelry has been passed down through generations, maintaining the same commitment to quality and authenticity that defined our earliest days.',
    'about.mission.title': 'Our Mission',
    'about.mission.content': 'To provide a trusted, transparent, and prestigious platform where collectors and enthusiasts can discover, acquire, and sell the worlds finest luxury items with complete confidence and exceptional service.',
    'about.team.title': 'Leadership Team',
    'about.team.member1.name': 'James Richardson',
    'about.team.member1.role': 'Chief Executive Officer',
    'about.team.member2.name': 'Sarah Chen',
    'about.team.member2.role': 'Head of Authentication',
    'about.team.member3.name': 'Michael Torres',
    'about.team.member3.role': 'Director of Auctions',
    'about.values.title': 'Our Core Values',
    'about.values.value1': 'Integrity & Trust',
    'about.values.value2': 'Excellence & Quality',
    'about.values.value3': 'Client-First Service',
    'about.stats.years': '38+',
    'about.stats.yearsLabel': 'Years of Excellence',
    'about.stats.auctions': '15K+',
    'about.stats.auctionsLabel': 'Successful Auctions',
    'about.stats.countries': '45+',
    'about.stats.countriesLabel': 'Countries Served',
    'about.stats.clients': '50K+',
    'about.stats.clientsLabel': 'Satisfied Clients',
    'about.contact.title': 'Get in Touch',
    'about.contact.description': 'Have questions about our auctions or services? We would love to hear from you.',
    'about.contact.name': 'Your Name',
    'about.contact.email': 'Email Address',
    'about.contact.subject': 'Subject',
    'about.contact.message': 'Your Message',
    'about.contact.send': 'Send Message',
    'about.contact.sending': 'Sending...',
    'about.contact.success': 'Your message has been sent successfully! We will get back to you soon.',
    'about.contact.error': 'Failed to send message. Please try again.',
    'about.contact.loginRequired': 'Please log in to send a message.',
    'about.contact.subjectGeneral': 'General Inquiry',
    'about.contact.subjectAuction': 'Auction Question',
    'about.contact.subjectSelling': 'Selling an Item',
    'about.contact.subjectAppraisal': 'Appraisal Request',
    'about.footer.contactInfo': 'Contact Information',
    'about.footer.followUs': 'Follow Us',
    'about.footer.address': 'Pearl Tower, West Bay, Doha, Qatar',
    'about.footer.businessHours': 'Business Hours',
    'about.footer.weekdays': 'Sunday - Thursday: 9:00 AM - 6:00 PM',
    'about.footer.saturday': 'Friday: 2:00 PM - 6:00 PM',
    'about.footer.sunday': 'Saturday: Closed',
    'about.footer.liveChat': 'Live Chat',
    'about.footer.chatOnline': 'We are online now',
    'about.footer.chatHours': 'Available during business hours',
    'about.trustpilot.excellent': 'Excellent',
    'about.trustpilot.reviews': '2,847 reviews',
    'features.trusted.title': 'Trusted Worldwide',
    'features.trusted.description': 'We are a registered company that holds a corporation\'s license compliant with all Australian Business Laws, Audit Systems & Fair-Trading Practices under the Auctioneers Act 2014.',
    'features.expert.title': 'Expert Advice',
    'features.expert.description': 'We offer expert advice and valuation services to help you learn the correct value of your items. Contact us for professional appraisals and guidance.',
    'features.premium.title': 'Premium Selection',
    'features.premium.description': 'GIA Certified Diamonds, Fine Jewellery & Big Brand Swiss Watches. Get your desired items at exceptional values, well below retail prices.',
    'footer.quickLinks': 'Quick Links',
    'footer.services': 'Services',
    'footer.contact': 'Contact',
    'footer.copyright': 'Crown Auctions. All rights reserved. Licensed under the Auctioneers Act 2014.',
    'featured.title': 'Featured Auctions',
    'featured.subtitle': 'Browse our current live auctions and place your bids',
    'featured.all': 'All',
    'featured.jewellery': 'Jewellery',
    'featured.watches': 'Watches',
    'featured.diamonds': 'Diamonds',
    'featured.noAuctions': 'No auctions found in this category. Check back soon!',
    'auction.1.title': 'Platinum Diamond Solitaire Ring - 2.5 Carat',
    'auction.2.title': 'Swiss Chronograph Watch - Black Leather Strap',
    'auction.3.title': '18K Gold Diamond Pendant Necklace',
    'auction.4.title': 'Vintage Rolex Datejust - 18K Gold',
    'auction.5.title': 'Sapphire & Diamond Drop Earrings - White Gold',
    'auction.6.title': 'GIA Certified 3.2 Carat Loose Diamond - VS1',
    'auction.startingPrice': 'Starting Price',
    'auction.currentBid': 'Current Bid',
    'auction.bids': 'bids',
    'auction.timeLeft': 'Time Left',
    'auction.active': 'Active',
    'auction.paused': 'Paused',
    // Admin Dashboard
    'admin.title': 'Admin Dashboard',
    'admin.subtitle': 'Manage and review auction submissions',
    'admin.createAuction': 'Create New Auction',
    'admin.pendingReview': 'Pending Review',
    'admin.approved': 'Approved for Sell/Auction',
    'admin.scheduled': 'Scheduled',
    'admin.rejected': 'Rejected',
    'admin.pending': 'Pending',
    'admin.appraisers': 'Appraisers',
    'admin.noPending': 'No pending auctions',
    'admin.noScheduled': 'No scheduled auctions',
    'admin.noApproved': 'No approved auctions',
    'admin.noRejected': 'No rejected auctions',
    'admin.noAppraisers': 'No appraiser applications yet',
    'admin.category': 'Category',
    'admin.startingPrice': 'Starting Price',
    'admin.currentBid': 'Current Bid',
    'admin.scheduledStart': 'Scheduled Start',
    'admin.submitted': 'Submitted',
    'admin.rejectionReason': 'Rejection Reason',
    'admin.resubmission': 'Resubmission',
    'admin.saveComment': 'Save Comment',
    'admin.saving': 'Saving...',
    'admin.viewDetails': 'View Details',
    'admin.edit': 'Edit',
    'admin.approve': 'Approve',
    'admin.reject': 'Reject',
    'admin.pauseAuction': 'Pause Auction',
    'admin.resumeAuction': 'Resume Auction',
    'admin.startAuction': 'Start Auction',
    'admin.live': 'Live',
    'admin.rejectDialog.title': 'Reject Auction',
    'admin.rejectDialog.description': 'Please provide a reason for rejecting this auction. This will be visible to the submitter.',
    'admin.rejectDialog.placeholder': 'Enter rejection reason...',
    'admin.rejectDialog.cancel': 'Cancel',
    'admin.rejectDialog.rejecting': 'Rejecting...',
    'admin.rejectDialog.confirm': 'Reject Auction',
    // Appraiser section
    'admin.appraiser.email': 'Email',
    'admin.appraiser.phone': 'Phone',
    'admin.appraiser.experience': 'Experience',
    'admin.appraiser.years': 'years',
    'admin.appraiser.applied': 'Applied',
    'admin.appraiser.specializations': 'Specializations',
    'admin.appraiser.certifications': 'Certifications',
    'admin.appraiser.previousEmployers': 'Previous Employers',
    'admin.appraiser.references': 'Professional References',
    'admin.appraiser.coverLetter': 'Cover Letter',
    'admin.appraiser.adminNotes': 'Admin Notes',
    'admin.appraiser.notesPlaceholder': 'Add notes about this application...',
    'admin.appraiser.reviewedOn': 'Reviewed on',
    // Submit Auction
    'submit.title': 'Submit Auction Item',
    'submit.description': 'Submit your luxury item for auction approval. All submissions are reviewed by our team.',
    'submit.prefilled': 'Form pre-filled with your previous submission data',
    'submit.basicInfo': 'Basic Information',
    'submit.itemTitle': 'Title',
    'submit.titlePlaceholder': 'e.g., Rolex Submariner 116610LN',
    'submit.category': 'Category',
    'submit.selectCategory': 'Select category',
    'submit.watches': 'Watches',
    'submit.jewelry': 'Jewelry',
    'submit.diamonds': 'Diamonds',
    'submit.luxuryGoods': 'Luxury Goods',
    'submit.itemDescription': 'Description',
    'submit.descriptionPlaceholder': 'Detailed description of the item, including condition, provenance, and any notable features...',
    'submit.minChars': 'Minimum 20 characters',
    'submit.pricing': 'Pricing',
    'submit.startingPrice': 'Starting Price (USD)',
    'submit.minIncrement': 'Minimum Bid Increment (USD)',
    'submit.endDateTime': 'Auction End Date & Time',
    'submit.images': 'Images',
    'submit.imagesHelp': 'Upload high-quality images (max 10 images, 5MB each, JPG/PNG/WEBP)',
    'submit.upload': 'Upload',
    'submit.specifications': 'Specifications (Optional)',
    'submit.specLabel': 'Label (e.g., Brand)',
    'submit.specValue': 'Value (e.g., Rolex)',
    'submit.certificates': 'Certificates (Optional)',
    'submit.certName': 'Certificate Name',
    'submit.certIssuer': 'Issuer',
    'submit.add': 'Add',
    'submit.submitting': 'Submitting...',
    'submit.submitForApproval': 'Submit for Approval',
    'submit.cancel': 'Cancel',
    // Testimonials
    'testimonials.title': 'What Our Clients Say',
    'testimonials.1.text': 'What a great selection there was, I purchased 2 items and was very satisfied. Thank you!',
    'testimonials.1.author': 'Sarah M.',
    'testimonials.2.text': 'Professional service and authentic luxury items. The authentication process gave me complete confidence in my purchase.',
    'testimonials.2.author': 'James R.',
    'testimonials.3.text': "I've been buying from Crown Auctions for years. Their Swiss watch collection is unmatched and prices are exceptional.",
    'testimonials.3.author': 'Michael K.',
    // Footer
    'footer.tagline': 'Specialising in Fine Jewellery, Diamonds, and Swiss Watch Auctions',
    'footer.buyers': 'Buyers',
    'footer.sellers': 'Sellers',
    'footer.browseAuctions': 'Browse Auctions',
    'footer.valuationServices': 'Valuation Services',
    'footer.sellWithUs': 'Sell With Us',
    'footer.authentication': 'Authentication',
    'footer.becomeAppraiser': 'Become an Appraiser',
    'footer.email': 'Email',
    'footer.phone': 'Phone',
    'footer.licensedAuctioneer': 'Licensed Auctioneer',
    // Dashboard
    'dashboard.signOut': 'Sign Out',
    'dashboard.profile': 'Profile',
    'dashboard.mySubmissions': 'My Submissions',
    'dashboard.watchlist': 'Watchlist',
    'dashboard.myBids': 'My Bids',
    'dashboard.profileInfo': 'Profile Information',
    'dashboard.updateDetails': 'Update your personal details',
    'dashboard.fullName': 'Full Name',
    'dashboard.email': 'Email',
    'dashboard.phone': 'Phone',
    'dashboard.updating': 'Updating...',
    'dashboard.updateProfile': 'Update Profile',
    'dashboard.noSubmissions': 'No auction submissions yet',
    'dashboard.submitFirst': 'Submit Your First Item',
    'dashboard.pendingReview': 'Pending Review',
    'dashboard.pending': 'Pending',
    'dashboard.resubmission': 'Resubmission',
    'dashboard.startingPrice': 'Starting Price',
    'dashboard.submitted': 'Submitted',
    'dashboard.pendingMessage': "Your submission is being reviewed by our team. You'll receive an email once it's processed.",
    'dashboard.withdrawing': 'Withdrawing...',
    'dashboard.withdrawSubmission': 'Withdraw Submission',
    'dashboard.approvedLive': 'Approved & Live',
    'dashboard.live': 'Live',
    'dashboard.currentBid': 'Current Bid',
    'dashboard.approved': 'Approved',
    'dashboard.ends': 'Ends',
    'dashboard.viewAuction': 'View Auction',
    'dashboard.notApproved': 'Not Approved',
    'dashboard.rejected': 'Rejected',
    'dashboard.rejectionReason': 'Reason for rejection',
    'dashboard.submitAnother': 'Submit Another Item',
    'dashboard.noSavedAuctions': 'No saved auctions yet',
    'dashboard.browseAuctions': 'Browse Auctions',
    'dashboard.savedOn': 'Saved on',
    'dashboard.remove': 'Remove',
    'dashboard.noActiveBids': 'No active bids',
    'dashboard.winning': 'Winning',
    'dashboard.outbid': 'Outbid',
    'dashboard.yourHighestBid': 'Your highest bid',
    'dashboard.currentHighest': 'Current highest',
    'dashboard.lastBid': 'Last bid',
    'dashboard.bidsPlaced': 'bids placed',
    'dashboard.view': 'View',
    'dashboard.rebidNow': 'Rebid Now',
    'dashboard.user': 'User',
    'dashboard.auction': 'Auction',
    // Auction Detail
    'auctionDetail.backToAuctions': 'Back to Auctions',
    'auctionDetail.notFound': 'Auction Not Found',
    'auctionDetail.returnHome': 'Return to Home',
    'auctionDetail.startingPrice': 'Starting Price',
    'auctionDetail.currentBid': 'Current Bid',
    'auctionDetail.bidPlaced': 'bid placed',
    'auctionDetail.bidsPlaced': 'bids placed',
    'auctionDetail.endsIn': 'Ends in',
    'auctionDetail.placeYourBid': 'Place Your Bid',
    'auctionDetail.auctionPaused': 'Auction Paused',
    'auctionDetail.auctionPausedMessage': 'This auction has been temporarily paused by administrators. Bidding is currently disabled.',
    'auctionDetail.adminCannotBid': 'Administrators cannot place bids to maintain auction integrity and avoid conflicts of interest.',
    'auctionDetail.yourBidAmount': 'Your Bid Amount (AUD)',
    'auctionDetail.minimumBid': 'Minimum bid',
    'auctionDetail.increment': 'increment',
    'auctionDetail.quickBid': 'Quick Bid',
    'auctionDetail.minBid': 'Min Bid',
    'auctionDetail.placeBid': 'Place Bid',
    'auctionDetail.biddingDisabled': 'Bidding Disabled',
    'auctionDetail.specifications': 'Specifications',
    'auctionDetail.authentication': 'Authentication & Certificates',
    'auctionDetail.issuedBy': 'Issued by',
    'auctionDetail.bidHistory': 'Bid History',
    'auctionDetail.loadingBidHistory': 'Loading bid history...',
    'auctionDetail.noBidsYet': 'No bids placed yet. Be the first to bid!',
    'auctionDetail.bidder': 'Bidder',
    'auctionDetail.bidAmount': 'Bid Amount',
    'auctionDetail.time': 'Time',
    'auctionDetail.you': 'You',
    'auctionDetail.highest': 'Highest',
    'auctionDetail.signInRequired': 'Sign In Required',
    'auctionDetail.signInToBid': 'Please sign in to place a bid.',
    'auctionDetail.invalidBid': 'Invalid Bid',
    'auctionDetail.enterValidBid': 'Please enter a valid bid amount.',
    'auctionDetail.description': 'Description',
    // Certificate names
    'cert.giaReport': 'GIA Diamond Report',
    'cert.platinumHallmark': 'Platinum Hallmark',
    'cert.swissMade': 'Swiss Made Certificate',
    'cert.warranty': 'Warranty Card',
    'cert.goldAssay': 'Gold Assay Certificate',
    'cert.authenticityReport': 'Authenticity Report',
    'cert.appraisalReport': 'Appraisal Report',
    'cert.insuranceValuation': 'Insurance Valuation',
    // Certificate issuers
    'cert.issuer.gia': 'Gemological Institute of America',
    'cert.issuer.australianAssay': 'Australian Assay Office',
    'cert.issuer.swissWatch': 'Federation of the Swiss Watch Industry',
    'cert.issuer.manufacturer': 'Manufacturer',
    'cert.issuer.igi': 'International Gemological Institute',
    'cert.issuer.hrd': 'HRD Antwerp',
    // Categories
    'category.watches': 'Watches',
    'category.jewellery': 'Jewellery',
    'category.diamonds': 'Diamonds',
    'category.rings': 'Rings',
    'category.necklaces': 'Necklaces',
    'category.bracelets': 'Bracelets',
    'category.earrings': 'Earrings',
    'category.other': 'Other',
    // Specifications
    'specs.title': 'Specifications',
    'specs.basicInfo': 'Basic Info',
    'specs.caliber': 'Caliber',
    'specs.case': 'Case',
    'specs.braceletStrap': 'Bracelet/Strap',
    'specs.functions': 'Functions',
    'specs.otherDetails': 'Other Details',
    'specs.conditionVerified': 'Condition Verified',
    'specs.conditionMessage': 'This item has been inspected and authenticated by our expert team. All specifications have been verified for accuracy.',
    'specs.productSafety': 'Product Safety',
    'specs.showInfo': 'Show Information',
    // Spec Labels
    'spec.brand': 'Brand',
    'spec.model': 'Model',
    'spec.referenceNumber': 'Reference Number',
    'spec.yearOfProduction': 'Year of Production',
    'spec.condition': 'Condition',
    'spec.scopeOfDelivery': 'Scope of Delivery',
    'spec.gender': 'Gender',
    'spec.location': 'Location',
    'spec.movement': 'Movement',
    'spec.caliber': 'Caliber',
    'spec.powerReserve': 'Power Reserve',
    'spec.numberOfJewels': 'Number of Jewels',
    'spec.caseMaterial': 'Case Material',
    'spec.caseDiameter': 'Case Diameter',
    'spec.caseThickness': 'Case Thickness',
    'spec.waterResistance': 'Water Resistance',
    'spec.bezelMaterial': 'Bezel Material',
    'spec.crystal': 'Crystal',
    'spec.dial': 'Dial',
    'spec.dialNumerals': 'Dial Numerals',
    'spec.braceletMaterial': 'Bracelet Material',
    'spec.braceletColor': 'Bracelet Color',
    'spec.clasp': 'Clasp',
    'spec.claspMaterial': 'Clasp Material',
    'spec.chronograph': 'Chronograph',
    'spec.dateDisplay': 'Date Display',
    'spec.listingCode': 'Listing Code',
    'spec.metal': 'Metal',
    'spec.diamondWeight': 'Diamond Weight',
    'spec.colorGrade': 'Color Grade',
    'spec.clarity': 'Clarity',
    'spec.cut': 'Cut',
    'spec.ringSize': 'Ring Size',
    'spec.caratWeight': 'Carat Weight',
    'spec.shape': 'Shape',
    'spec.polish': 'Polish',
    'spec.symmetry': 'Symmetry',
    'spec.fluorescence': 'Fluorescence',
    'spec.chainLength': 'Chain Length',
    'spec.pendantSize': 'Pendant Size',
    'spec.claspType': 'Clasp Type',
    'spec.totalDiamondWeight': 'Total Diamond Weight',
    'spec.diamondQuality': 'Diamond Quality',
    'spec.sapphireWeight': 'Sapphire Weight',
    'spec.sapphireOrigin': 'Sapphire Origin',
    'spec.earringLength': 'Earring Length',
    'spec.closureType': 'Closure Type',
    // Appraiser Apply Form
    'appraiserApply.title': 'Apply as Watch Appraiser',
    'appraiserApply.subtitle': 'Join our team of expert appraisers and help authenticate luxury timepieces',
    'appraiserApply.fullName': 'Full Name',
    'appraiserApply.email': 'Email',
    'appraiserApply.phone': 'Phone Number',
    'appraiserApply.experience': 'Years of Experience',
    'appraiserApply.specializations': 'Specializations',
    'appraiserApply.luxuryWatches': 'Luxury Watches',
    'appraiserApply.fineJewelry': 'Fine Jewelry',
    'appraiserApply.diamonds': 'Diamonds',
    'appraiserApply.vintageTimepieces': 'Vintage Timepieces',
    'appraiserApply.estateJewelry': 'Estate Jewelry',
    'appraiserApply.designerPieces': 'Designer Pieces',
    'appraiserApply.certifications': 'Certifications & Qualifications',
    'appraiserApply.certificationsPlaceholder': 'List your relevant certifications, degrees, and qualifications',
    'appraiserApply.previousEmployers': 'Previous Employers',
    'appraiserApply.previousEmployersPlaceholder': 'List your previous employers in the luxury watch or jewelry industry',
    'appraiserApply.references': 'Professional References',
    'appraiserApply.referencesPlaceholder': 'Provide contact information for professional references',
    'appraiserApply.coverLetter': 'Cover Letter',
    'appraiserApply.coverLetterPlaceholder': "Tell us why you'd like to join our team and what makes you a great appraiser",
    'appraiserApply.submitting': 'Submitting...',
    'appraiserApply.submit': 'Submit Application',
    'appraiserApply.cancel': 'Cancel',
    'appraiserApply.signInError': 'Please sign in to apply',
    'appraiserApply.specializationError': 'Please select at least one specialization',
    'appraiserApply.success': 'Application submitted successfully!',
    'appraiserApply.error': 'Failed to submit application',
    // Admin Create Auction
    'adminCreateAuction.createNewAuction': 'Create New Auction',
    'adminCreateAuction.editScheduledAuction': 'Edit Scheduled Auction',
    'adminCreateAuction.createDescription': 'Create an auction directly as approved and active',
    'adminCreateAuction.editDescription': 'Update auction details before it goes live',
    'adminCreateAuction.basicInformation': 'Basic Information',
    'adminCreateAuction.title': 'Title',
    'adminCreateAuction.titlePlaceholder': 'e.g., Vintage Rolex Submariner',
    'adminCreateAuction.category': 'Category',
    'adminCreateAuction.selectCategory': 'Select a category',
    'adminCreateAuction.watches': 'Watches',
    'adminCreateAuction.jewelry': 'Jewelry',
    'adminCreateAuction.diamonds': 'Diamonds',
    'adminCreateAuction.luxuryItems': 'Luxury Items',
    'adminCreateAuction.description': 'Description',
    'adminCreateAuction.descriptionPlaceholder': 'Detailed description of the item...',
    'adminCreateAuction.schedulingPricing': 'Scheduling & Pricing',
    'adminCreateAuction.schedulingNote': 'Set a future start time to schedule the auction. It will automatically go live at the specified time.',
    'adminCreateAuction.startingPrice': 'Starting Price ($)',
    'adminCreateAuction.startingPricePlaceholder': 'e.g., 5000',
    'adminCreateAuction.minimumIncrement': 'Minimum Bid Increment ($)',
    'adminCreateAuction.minimumIncrementPlaceholder': 'e.g., 100',
    'adminCreateAuction.startTime': 'Start Time',
    'adminCreateAuction.endTime': 'End Time',
    'adminCreateAuction.images': 'Images',
    'adminCreateAuction.imagesNote': 'Upload up to 5 images (first image will be the main image)',
    'adminCreateAuction.clickToUpload': 'Click to upload images (Max 5)',
    'adminCreateAuction.mainImage': 'Main Image',
    'adminCreateAuction.specifications': 'Specifications',
    'adminCreateAuction.addSpecification': 'Add Specification',
    'adminCreateAuction.labelPlaceholder': 'Label (e.g., Brand)',
    'adminCreateAuction.valuePlaceholder': 'Value (e.g., Rolex)',
    'adminCreateAuction.certificates': 'Certificates',
    'adminCreateAuction.addCertificate': 'Add Certificate',
    'adminCreateAuction.certificateNamePlaceholder': 'Certificate Name',
    'adminCreateAuction.issuerPlaceholder': 'Issuer',
    'adminCreateAuction.createAuction': 'Create Auction',
    'adminCreateAuction.updateAuction': 'Update Auction',
    'adminCreateAuction.creatingAuction': 'Creating Auction...',
    'adminCreateAuction.updatingAuction': 'Updating Auction...',
    'adminCreateAuction.cancel': 'Cancel',
    'adminCreateAuction.maxImagesError': 'Maximum 5 images allowed',
    'adminCreateAuction.endTimeError': 'End time must be after start time',
    'adminCreateAuction.uploadImageError': 'Please upload at least one image',
    'adminCreateAuction.onlyScheduledEditable': 'Only scheduled auctions can be edited',
    'adminCreateAuction.loadAuctionError': 'Failed to load auction data',
    'adminCreateAuction.auctionUpdatedScheduled': 'Auction updated! It will go live at',
    'adminCreateAuction.auctionUpdatedLive': 'Auction updated successfully and is now live!',
    'adminCreateAuction.auctionScheduled': 'Auction scheduled successfully! It will go live at',
    'adminCreateAuction.auctionCreatedLive': 'Auction created successfully and is now live!',
    'adminCreateAuction.createError': 'Failed to create auction',
    // Process Steps
    'process.badge': 'How It Works',
    'process.title': '1 → 2 → 3 → 4 → 5',
    'process.subtitle': 'From submission to payment, we handle everything with care and expertise',
    'process.stepLabel': 'STEP',
    'process.step1.title': 'Fill Out the Form',
    'process.step1.description': 'Begin your journey by completing our simple online submission form. Provide details about your luxury item including photos, condition, and any documentation.',
    'process.step1.detail1': 'Complete the secure online submission form with item details',
    'process.step1.detail2': 'Upload high-quality photos from multiple angles',
    'process.step1.detail3': 'Include certificates, appraisals, or provenance documentation',
    'process.step2.title': 'Schedule Shipping',
    'process.step2.description': 'Once approved, we coordinate secure, insured shipping to our facility. Your item is protected every step of the way.',
    'process.step2.detail1': 'Receive a prepaid, fully insured shipping label',
    'process.step2.detail2': 'Professional packaging guidelines provided',
    'process.step2.detail3': 'Real-time tracking from pickup to delivery',
    'process.step3.title': 'Prep for Sale',
    'process.step3.description': 'Our expert team professionally photographs, authenticates, and catalogs your item to maximize buyer interest and value.',
    'process.step3.detail1': 'Professional photography in our studio',
    'process.step3.detail2': 'Expert authentication and grading',
    'process.step3.detail3': 'Compelling listing copy written by specialists',
    'process.step4.title': 'Online Auction',
    'process.step4.description': 'Your item goes live to our global network of qualified buyers. Watch as bids come in and your item finds its new home.',
    'process.step4.detail1': 'Exposure to thousands of verified collectors',
    'process.step4.detail2': 'Real-time bidding with live updates',
    'process.step4.detail3': 'Dedicated support throughout the auction',
    'process.step5.title': 'Get Paid',
    'process.step5.description': 'Once sold, receive fast, secure payment. Our transparent process ensures you get paid quickly with no hidden fees.',
    'process.step5.detail1': 'Fast payment within 7 business days of sale',
    'process.step5.detail2': 'Multiple payment options including wire transfer',
    'process.step5.detail3': 'Detailed transaction report for your records',
    'process.cta': 'Enter Online Auction Today.',
    'process.ctaSubtext': 'Submit your luxury item and start your auction journey',
  },
  ar: {
    'nav.home': 'الرئيسية',
    'nav.about': 'من نحن',
    'nav.buyers': 'المشترون',
    'nav.sellers': 'البائعون',
    'nav.browseAuctions': 'تصفح المزادات',
    'nav.auctions': 'المزادات',
    'nav.contact': 'اتصل بنا',
    'hero.title': 'مزادات كراون',
    'hero.subtitle': 'مخزون تجزئة فائض وتصفيات من تجار مرخصين متعددين',
    'hero.cta': 'ابدأ اليوم',
    'hero.howItWorks': 'كيف يعمل',
    'hero.step1.title': 'أخبرنا عن قطعك',
    'hero.step1.desc': 'قم بتضمين الصور وأي مستندات أو شهادات ذات صلة. المعلومات التفصيلية ستحسن مستوى خدمتنا.',
    'hero.step2.title': 'حدد موعداً للزيارة',
    'hero.step2.desc': 'اختر تاريخاً ووقتاً للقاء خبيرنا بشكل خاص. احصل على تقييم مجاني لقطعك دون أي التزام بالبيع.',
    'hero.step3.title': 'قابل خبيراً للحصول على عرض',
    'hero.step3.desc': 'بعد مراجعة قطعك، سنقدم لك عرض شراء. لا توجد رسوم أو عمولات على خدمتنا.',
    'hero.step4.title': 'احصل على المال',
    'hero.step4.desc': 'احصل على الدفع الفوري عبر التحويل البنكي.',
    'itemCategory.title': 'ما نوع القطعة التي لديك؟',
    'itemCategory.subtitle': 'اختر الفئة التي تصف قطعتك بشكل أفضل',
    'itemCategory.diamonds': 'الماس',
    'itemCategory.diamondsDesc': 'الماس السائب والأحجار المعتمدة',
    'itemCategory.watches': 'الساعات',
    'itemCategory.watchesDesc': 'الساعات الفاخرة والسويسرية',
    'itemCategory.jewelry': 'المجوهرات',
    'itemCategory.jewelryDesc': 'القلائد والأساور والأقراط',
    'itemCategory.rings': 'الخواتم',
    'itemCategory.ringsDesc': 'خواتم الخطوبة والزفاف',
    'itemCategory.luxury': 'القطع الفاخرة',
    'itemCategory.luxuryDesc': 'القطع التصميمية والتحف',
    'itemCategory.other': 'أخرى',
    'itemCategory.otherDesc': 'قطع قيمة أخرى',
    'itemCategory.hint': 'سيساعدك خبراؤنا في تحديد أفضل فئة لقطعتك',
    'about.title': 'عن مزادات كراون',
    'about.description': 'مزادات كراون هي دار مزادات فاخرة رائدة متخصصة في المجوهرات الفاخرة والماس والساعات السويسرية. مع عقود من الخبرة، نربط المشترين المميزين بالقطع الاستثنائية.',
    'about.history.title': 'تاريخنا',
    'about.history.content': 'تأسست مزادات كراون في عام 1985، بدأت كشركة مجوهرات عائلية صغيرة في سيدني. على مدى ما يقرب من أربعة عقود، نمونا لنصبح واحدة من أكثر دور المزادات احتراماً في منطقة آسيا والمحيط الهادئ. شغف مؤسسينا بالساعات الرائعة والمجوهرات الفاخرة انتقل عبر الأجيال، محافظين على نفس الالتزام بالجودة والأصالة التي ميزت أيامنا الأولى.',
    'about.mission.title': 'مهمتنا',
    'about.mission.content': 'توفير منصة موثوقة وشفافة ومرموقة حيث يمكن لهواة الجمع والمتحمسين اكتشاف والحصول على وبيع أفخم القطع الفاخرة في العالم بثقة تامة وخدمة استثنائية.',
    'about.team.title': 'فريق القيادة',
    'about.team.member1.name': 'جيمس ريتشاردسون',
    'about.team.member1.role': 'الرئيس التنفيذي',
    'about.team.member2.name': 'سارة تشين',
    'about.team.member2.role': 'رئيسة قسم التوثيق',
    'about.team.member3.name': 'مايكل توريس',
    'about.team.member3.role': 'مدير المزادات',
    'about.values.title': 'قيمنا الأساسية',
    'about.values.value1': 'النزاهة والثقة',
    'about.values.value2': 'التميز والجودة',
    'about.values.value3': 'خدمة العميل أولاً',
    'about.stats.years': '+38',
    'about.stats.yearsLabel': 'سنة من التميز',
    'about.stats.auctions': '+15 ألف',
    'about.stats.auctionsLabel': 'مزاد ناجح',
    'about.stats.countries': '+45',
    'about.stats.countriesLabel': 'دولة نخدمها',
    'about.stats.clients': '+50 ألف',
    'about.stats.clientsLabel': 'عميل راضٍ',
    'about.contact.title': 'تواصل معنا',
    'about.contact.description': 'هل لديك أسئلة حول مزاداتنا أو خدماتنا؟ يسعدنا سماع منك.',
    'about.contact.name': 'اسمك',
    'about.contact.email': 'البريد الإلكتروني',
    'about.contact.subject': 'الموضوع',
    'about.contact.message': 'رسالتك',
    'about.contact.send': 'إرسال الرسالة',
    'about.contact.sending': 'جاري الإرسال...',
    'about.contact.success': 'تم إرسال رسالتك بنجاح! سنتواصل معك قريباً.',
    'about.contact.error': 'فشل في إرسال الرسالة. يرجى المحاولة مرة أخرى.',
    'about.contact.loginRequired': 'يرجى تسجيل الدخول لإرسال رسالة.',
    'about.contact.subjectGeneral': 'استفسار عام',
    'about.contact.subjectAuction': 'سؤال عن المزاد',
    'about.contact.subjectSelling': 'بيع قطعة',
    'about.contact.subjectAppraisal': 'طلب تقييم',
    'about.footer.contactInfo': 'معلومات الاتصال',
    'about.footer.followUs': 'تابعنا',
    'about.footer.address': 'برج اللؤلؤة، الخليج الغربي، الدوحة، قطر',
    'about.footer.businessHours': 'ساعات العمل',
    'about.footer.weekdays': 'الأحد - الخميس: ٩:٠٠ ص - ٦:٠٠ م',
    'about.footer.saturday': 'الجمعة: ٢:٠٠ م - ٦:٠٠ م',
    'about.footer.sunday': 'السبت: مغلق',
    'about.footer.liveChat': 'الدردشة المباشرة',
    'about.footer.chatOnline': 'نحن متصلون الآن',
    'about.footer.chatHours': 'متاح خلال ساعات العمل',
    'about.trustpilot.excellent': 'ممتاز',
    'about.trustpilot.reviews': '٢٬٨٤٧ تقييم',
    'features.trusted.title': 'موثوق به عالمياً',
    'features.trusted.description': 'نحن شركة مسجلة تمتلك ترخيص شركة متوافق مع جميع قوانين الأعمال الأسترالية وأنظمة التدقيق وممارسات التجارة العادلة بموجب قانون البائعين بالمزاد 2014.',
    'features.expert.title': 'مشورة الخبراء',
    'features.expert.description': 'نقدم مشورة الخبراء وخدمات التقييم لمساعدتك في معرفة القيمة الصحيحة لممتلكاتك. اتصل بنا للحصول على تقييمات وإرشادات مهنية.',
    'features.premium.title': 'مجموعة مميزة',
    'features.premium.description': 'ماس معتمد من GIA، مجوهرات فاخرة وساعات سويسرية من علامات تجارية كبرى. احصل على القطع المرغوبة بأسعار استثنائية أقل بكثير من أسعار التجزئة.',
    'footer.quickLinks': 'روابط سريعة',
    'footer.services': 'الخدمات',
    'footer.contact': 'اتصل بنا',
    'footer.copyright': 'مزادات كراون. جميع الحقوق محفوظة. مرخص بموجب قانون البائعين بالمزاد 2014.',
    'featured.title': 'المزادات المميزة',
    'featured.subtitle': 'تصفح مزاداتنا الحية الحالية وقدم عروضك',
    'featured.all': 'الكل',
    'featured.jewellery': 'مجوهرات',
    'featured.watches': 'ساعات',
    'featured.diamonds': 'ماس',
    'featured.noAuctions': 'لا توجد مزادات في هذه الفئة. تحقق مرة أخرى قريباً!',
    'auction.1.title': 'خاتم بلاتيني بالماس المنفرد - 2.5 قيراط',
    'auction.2.title': 'ساعة كرونوغراف سويسرية - حزام جلد أسود',
    'auction.3.title': 'قلادة ذهب 18 قيراط بالماس',
    'auction.4.title': 'رولكس ديتجست كلاسيكية - ذهب 18 قيراط',
    'auction.5.title': 'أقراط ياقوت وماس - ذهب أبيض',
    'auction.6.title': 'ماسة فضفاضة معتمدة من GIA 3.2 قيراط - VS1',
    'auction.startingPrice': 'السعر الابتدائي',
    'auction.currentBid': 'المزايدة الحالية',
    'auction.bids': 'مزايدات',
    'auction.timeLeft': 'الوقت المتبقي',
    'auction.active': 'نشط',
    'auction.paused': 'متوقف',
    // Admin Dashboard
    'admin.title': 'لوحة تحكم المدير',
    'admin.subtitle': 'إدارة ومراجعة طلبات المزادات',
    'admin.createAuction': 'إنشاء مزاد جديد',
    'admin.pendingReview': 'قيد المراجعة',
    'admin.approved': 'معتمد للبيع/المزاد',
    'admin.scheduled': 'مجدول',
    'admin.rejected': 'مرفوض',
    'admin.pending': 'قيد الانتظار',
    'admin.appraisers': 'المقيّمون',
    'admin.noPending': 'لا توجد مزادات قيد الانتظار',
    'admin.noScheduled': 'لا توجد مزادات مجدولة',
    'admin.noApproved': 'لا توجد مزادات معتمدة',
    'admin.noRejected': 'لا توجد مزادات مرفوضة',
    'admin.noAppraisers': 'لا توجد طلبات مقيّمين بعد',
    'admin.category': 'الفئة',
    'admin.startingPrice': 'السعر الابتدائي',
    'admin.currentBid': 'المزايدة الحالية',
    'admin.scheduledStart': 'بداية مجدولة',
    'admin.submitted': 'تاريخ التقديم',
    'admin.rejectionReason': 'سبب الرفض',
    'admin.resubmission': 'إعادة تقديم',
    'admin.saveComment': 'حفظ التعليق',
    'admin.saving': 'جاري الحفظ...',
    'admin.viewDetails': 'عرض التفاصيل',
    'admin.edit': 'تعديل',
    'admin.approve': 'موافقة',
    'admin.reject': 'رفض',
    'admin.pauseAuction': 'إيقاف المزاد',
    'admin.resumeAuction': 'استئناف المزاد',
    'admin.startAuction': 'بدء المزاد',
    'admin.live': 'مباشر',
    'admin.rejectDialog.title': 'رفض المزاد',
    'admin.rejectDialog.description': 'يرجى تقديم سبب لرفض هذا المزاد. سيكون هذا مرئياً للمقدم.',
    'admin.rejectDialog.placeholder': 'أدخل سبب الرفض...',
    'admin.rejectDialog.cancel': 'إلغاء',
    'admin.rejectDialog.rejecting': 'جاري الرفض...',
    'admin.rejectDialog.confirm': 'رفض المزاد',
    // Appraiser section
    'admin.appraiser.email': 'البريد الإلكتروني',
    'admin.appraiser.phone': 'الهاتف',
    'admin.appraiser.experience': 'الخبرة',
    'admin.appraiser.years': 'سنوات',
    'admin.appraiser.applied': 'تاريخ التقديم',
    'admin.appraiser.specializations': 'التخصصات',
    'admin.appraiser.certifications': 'الشهادات',
    'admin.appraiser.previousEmployers': 'أصحاب العمل السابقون',
    'admin.appraiser.references': 'المراجع المهنية',
    'admin.appraiser.coverLetter': 'خطاب التغطية',
    'admin.appraiser.adminNotes': 'ملاحظات المدير',
    'admin.appraiser.notesPlaceholder': 'أضف ملاحظات حول هذا الطلب...',
    'admin.appraiser.reviewedOn': 'تمت المراجعة في',
    // Submit Auction
    'submit.title': 'تقديم عنصر للمزاد',
    'submit.description': 'قدم عنصرك الفاخر للموافقة على المزاد. يتم مراجعة جميع الطلبات من قبل فريقنا.',
    'submit.prefilled': 'تم ملء النموذج مسبقاً ببيانات تقديمك السابق',
    'submit.basicInfo': 'المعلومات الأساسية',
    'submit.itemTitle': 'العنوان',
    'submit.titlePlaceholder': 'مثال: رولكس سابمارينر 116610LN',
    'submit.category': 'الفئة',
    'submit.selectCategory': 'اختر الفئة',
    'submit.watches': 'ساعات',
    'submit.jewelry': 'مجوهرات',
    'submit.diamonds': 'ماس',
    'submit.luxuryGoods': 'سلع فاخرة',
    'submit.itemDescription': 'الوصف',
    'submit.descriptionPlaceholder': 'وصف تفصيلي للعنصر، بما في ذلك الحالة والمصدر وأي ميزات بارزة...',
    'submit.minChars': 'الحد الأدنى 20 حرفاً',
    'submit.pricing': 'التسعير',
    'submit.startingPrice': 'السعر الابتدائي (دولار)',
    'submit.minIncrement': 'الحد الأدنى لزيادة المزايدة (دولار)',
    'submit.endDateTime': 'تاريخ ووقت انتهاء المزاد',
    'submit.images': 'الصور',
    'submit.imagesHelp': 'حمّل صوراً عالية الجودة (حد أقصى 10 صور، 5 ميجابايت لكل صورة، JPG/PNG/WEBP)',
    'submit.upload': 'تحميل',
    'submit.specifications': 'المواصفات (اختياري)',
    'submit.specLabel': 'التسمية (مثال: العلامة التجارية)',
    'submit.specValue': 'القيمة (مثال: رولكس)',
    'submit.certificates': 'الشهادات (اختياري)',
    'submit.certName': 'اسم الشهادة',
    'submit.certIssuer': 'الجهة المصدرة',
    'submit.add': 'إضافة',
    'submit.submitting': 'جاري التقديم...',
    'submit.submitForApproval': 'تقديم للموافقة',
    'submit.cancel': 'إلغاء',
    // Testimonials
    'testimonials.title': 'ماذا يقول عملاؤنا',
    'testimonials.1.text': 'كان هناك تشكيلة رائعة، اشتريت قطعتين وكنت راضياً جداً. شكراً لكم!',
    'testimonials.1.author': 'سارة م.',
    'testimonials.2.text': 'خدمة احترافية وقطع فاخرة أصلية. منحتني عملية التوثيق ثقة كاملة في مشترياتي.',
    'testimonials.2.author': 'جيمس ر.',
    'testimonials.3.text': 'أشتري من مزادات كراون منذ سنوات. مجموعة الساعات السويسرية لديهم لا مثيل لها والأسعار استثنائية.',
    'testimonials.3.author': 'مايكل ك.',
    // Footer
    'footer.tagline': 'متخصصون في مزادات المجوهرات الفاخرة والماس والساعات السويسرية',
    'footer.buyers': 'المشترون',
    'footer.sellers': 'البائعون',
    'footer.browseAuctions': 'تصفح المزادات',
    'footer.valuationServices': 'خدمات التقييم',
    'footer.sellWithUs': 'بيع معنا',
    'footer.authentication': 'التوثيق',
    'footer.becomeAppraiser': 'كن مقيّماً',
    'footer.email': 'البريد الإلكتروني',
    'footer.phone': 'الهاتف',
    'footer.licensedAuctioneer': 'بائع مزادات مرخص',
    // Dashboard
    'dashboard.signOut': 'تسجيل الخروج',
    'dashboard.profile': 'الملف الشخصي',
    'dashboard.mySubmissions': 'طلباتي',
    'dashboard.watchlist': 'قائمة المتابعة',
    'dashboard.myBids': 'مزايداتي',
    'dashboard.profileInfo': 'معلومات الملف الشخصي',
    'dashboard.updateDetails': 'تحديث بياناتك الشخصية',
    'dashboard.fullName': 'الاسم الكامل',
    'dashboard.email': 'البريد الإلكتروني',
    'dashboard.phone': 'الهاتف',
    'dashboard.updating': 'جاري التحديث...',
    'dashboard.updateProfile': 'تحديث الملف الشخصي',
    'dashboard.noSubmissions': 'لا توجد طلبات مزادات بعد',
    'dashboard.submitFirst': 'قدم عنصرك الأول',
    'dashboard.pendingReview': 'قيد المراجعة',
    'dashboard.pending': 'قيد الانتظار',
    'dashboard.resubmission': 'إعادة تقديم',
    'dashboard.startingPrice': 'السعر الابتدائي',
    'dashboard.submitted': 'تاريخ التقديم',
    'dashboard.pendingMessage': 'يتم مراجعة طلبك من قبل فريقنا. ستتلقى بريداً إلكترونياً بمجرد معالجته.',
    'dashboard.withdrawing': 'جاري السحب...',
    'dashboard.withdrawSubmission': 'سحب الطلب',
    'dashboard.approvedLive': 'معتمد ومباشر',
    'dashboard.live': 'مباشر',
    'dashboard.currentBid': 'المزايدة الحالية',
    'dashboard.approved': 'معتمد',
    'dashboard.ends': 'ينتهي',
    'dashboard.viewAuction': 'عرض المزاد',
    'dashboard.notApproved': 'غير معتمد',
    'dashboard.rejected': 'مرفوض',
    'dashboard.rejectionReason': 'سبب الرفض',
    'dashboard.submitAnother': 'تقديم عنصر آخر',
    'dashboard.noSavedAuctions': 'لا توجد مزادات محفوظة بعد',
    'dashboard.browseAuctions': 'تصفح المزادات',
    'dashboard.savedOn': 'حُفظ في',
    'dashboard.remove': 'إزالة',
    'dashboard.noActiveBids': 'لا توجد مزايدات نشطة',
    'dashboard.winning': 'رابح',
    'dashboard.outbid': 'تم تجاوزك',
    'dashboard.yourHighestBid': 'أعلى مزايدتك',
    'dashboard.currentHighest': 'أعلى مزايدة حالية',
    'dashboard.lastBid': 'آخر مزايدة',
    'dashboard.bidsPlaced': 'مزايدات قُدمت',
    'dashboard.view': 'عرض',
    'dashboard.rebidNow': 'زايد الآن',
    'dashboard.user': 'مستخدم',
    'dashboard.auction': 'مزاد',
    // Auction Detail
    'auctionDetail.backToAuctions': 'العودة إلى المزادات',
    'auctionDetail.notFound': 'المزاد غير موجود',
    'auctionDetail.returnHome': 'العودة للرئيسية',
    'auctionDetail.startingPrice': 'السعر الابتدائي',
    'auctionDetail.currentBid': 'المزايدة الحالية',
    'auctionDetail.bidPlaced': 'مزايدة',
    'auctionDetail.bidsPlaced': 'مزايدات',
    'auctionDetail.endsIn': 'ينتهي خلال',
    'auctionDetail.placeYourBid': 'قدم مزايدتك',
    'auctionDetail.auctionPaused': 'المزاد متوقف',
    'auctionDetail.auctionPausedMessage': 'تم إيقاف هذا المزاد مؤقتاً من قبل المديرين. المزايدة معطلة حالياً.',
    'auctionDetail.adminCannotBid': 'لا يمكن للمديرين تقديم مزايدات للحفاظ على نزاهة المزاد وتجنب تضارب المصالح.',
    'auctionDetail.yourBidAmount': 'مبلغ مزايدتك (دولار أسترالي)',
    'auctionDetail.minimumBid': 'الحد الأدنى للمزايدة',
    'auctionDetail.increment': 'الزيادة',
    'auctionDetail.quickBid': 'مزايدة سريعة',
    'auctionDetail.minBid': 'الحد الأدنى',
    'auctionDetail.placeBid': 'قدم مزايدة',
    'auctionDetail.biddingDisabled': 'المزايدة معطلة',
    'auctionDetail.specifications': 'المواصفات',
    'auctionDetail.authentication': 'التوثيق والشهادات',
    'auctionDetail.issuedBy': 'صادر عن',
    'auctionDetail.bidHistory': 'سجل المزايدات',
    'auctionDetail.loadingBidHistory': 'جاري تحميل سجل المزايدات...',
    'auctionDetail.noBidsYet': 'لم يتم تقديم أي مزايدات بعد. كن أول من يزايد!',
    'auctionDetail.bidder': 'المزايد',
    'auctionDetail.bidAmount': 'مبلغ المزايدة',
    'auctionDetail.time': 'الوقت',
    'auctionDetail.you': 'أنت',
    'auctionDetail.highest': 'الأعلى',
    'auctionDetail.signInRequired': 'تسجيل الدخول مطلوب',
    'auctionDetail.signInToBid': 'يرجى تسجيل الدخول لتقديم مزايدة.',
    'auctionDetail.invalidBid': 'مزايدة غير صالحة',
    'auctionDetail.enterValidBid': 'يرجى إدخال مبلغ مزايدة صالح.',
    'auctionDetail.description': 'الوصف',
    // Certificate names
    'cert.giaReport': 'تقرير GIA للألماس',
    'cert.platinumHallmark': 'ختم البلاتين',
    'cert.swissMade': 'شهادة الصنع السويسري',
    'cert.warranty': 'بطاقة الضمان',
    'cert.goldAssay': 'شهادة فحص الذهب',
    'cert.authenticityReport': 'تقرير الأصالة',
    'cert.appraisalReport': 'تقرير التقييم',
    'cert.insuranceValuation': 'تقييم التأمين',
    // Certificate issuers
    'cert.issuer.gia': 'المعهد الأمريكي للأحجار الكريمة',
    'cert.issuer.australianAssay': 'مكتب الفحص الأسترالي',
    'cert.issuer.swissWatch': 'اتحاد صناعة الساعات السويسرية',
    'cert.issuer.manufacturer': 'الشركة المصنعة',
    'cert.issuer.igi': 'المعهد الدولي للأحجار الكريمة',
    'cert.issuer.hrd': 'HRD أنتويرب',
    // Categories
    'category.watches': 'الساعات',
    'category.jewellery': 'المجوهرات',
    'category.diamonds': 'الألماس',
    'category.rings': 'الخواتم',
    'category.necklaces': 'القلائد',
    'category.bracelets': 'الأساور',
    'category.earrings': 'الأقراط',
    'category.other': 'أخرى',
    // Specifications
    'specs.title': 'المواصفات',
    'specs.basicInfo': 'معلومات أساسية',
    'specs.caliber': 'العيار',
    'specs.case': 'العلبة',
    'specs.braceletStrap': 'السوار/الحزام',
    'specs.functions': 'الوظائف',
    'specs.otherDetails': 'تفاصيل أخرى',
    'specs.conditionVerified': 'تم التحقق من الحالة',
    'specs.conditionMessage': 'تم فحص هذه القطعة وتوثيقها من قبل فريق الخبراء لدينا. تم التحقق من جميع المواصفات للتأكد من دقتها.',
    'specs.productSafety': 'سلامة المنتج',
    'specs.showInfo': 'عرض المعلومات',
    // Spec Labels
    'spec.brand': 'العلامة التجارية',
    'spec.model': 'الموديل',
    'spec.referenceNumber': 'الرقم المرجعي',
    'spec.yearOfProduction': 'سنة الإنتاج',
    'spec.condition': 'الحالة',
    'spec.scopeOfDelivery': 'نطاق التسليم',
    'spec.gender': 'الجنس',
    'spec.location': 'الموقع',
    'spec.movement': 'الحركة',
    'spec.caliber': 'العيار',
    'spec.powerReserve': 'احتياطي الطاقة',
    'spec.numberOfJewels': 'عدد الجواهر',
    'spec.caseMaterial': 'مادة العلبة',
    'spec.caseDiameter': 'قطر العلبة',
    'spec.caseThickness': 'سمك العلبة',
    'spec.waterResistance': 'مقاومة الماء',
    'spec.bezelMaterial': 'مادة الإطار',
    'spec.crystal': 'الكريستال',
    'spec.dial': 'الميناء',
    'spec.dialNumerals': 'أرقام الميناء',
    'spec.braceletMaterial': 'مادة السوار',
    'spec.braceletColor': 'لون السوار',
    'spec.clasp': 'المشبك',
    'spec.claspMaterial': 'مادة المشبك',
    'spec.chronograph': 'كرونوغراف',
    'spec.dateDisplay': 'عرض التاريخ',
    'spec.listingCode': 'رمز القائمة',
    'spec.metal': 'المعدن',
    'spec.diamondWeight': 'وزن الألماس',
    'spec.colorGrade': 'درجة اللون',
    'spec.clarity': 'النقاء',
    'spec.cut': 'القطع',
    'spec.ringSize': 'مقاس الخاتم',
    'spec.caratWeight': 'الوزن بالقيراط',
    'spec.shape': 'الشكل',
    'spec.polish': 'التلميع',
    'spec.symmetry': 'التماثل',
    'spec.fluorescence': 'الفلورة',
    'spec.chainLength': 'طول السلسلة',
    'spec.pendantSize': 'حجم القلادة',
    'spec.claspType': 'نوع المشبك',
    'spec.totalDiamondWeight': 'إجمالي وزن الألماس',
    'spec.diamondQuality': 'جودة الألماس',
    'spec.sapphireWeight': 'وزن الياقوت',
    'spec.sapphireOrigin': 'أصل الياقوت',
    'spec.earringLength': 'طول القرط',
    'spec.closureType': 'نوع الإغلاق',
    // Appraiser Apply Form
    'appraiserApply.title': 'التقدم كمقيّم ساعات',
    'appraiserApply.subtitle': 'انضم إلى فريقنا من المقيّمين الخبراء وساعد في توثيق الساعات الفاخرة',
    'appraiserApply.fullName': 'الاسم الكامل',
    'appraiserApply.email': 'البريد الإلكتروني',
    'appraiserApply.phone': 'رقم الهاتف',
    'appraiserApply.experience': 'سنوات الخبرة',
    'appraiserApply.specializations': 'التخصصات',
    'appraiserApply.luxuryWatches': 'ساعات فاخرة',
    'appraiserApply.fineJewelry': 'مجوهرات راقية',
    'appraiserApply.diamonds': 'ماس',
    'appraiserApply.vintageTimepieces': 'ساعات كلاسيكية',
    'appraiserApply.estateJewelry': 'مجوهرات التركات',
    'appraiserApply.designerPieces': 'قطع المصممين',
    'appraiserApply.certifications': 'الشهادات والمؤهلات',
    'appraiserApply.certificationsPlaceholder': 'اذكر شهاداتك ودرجاتك ومؤهلاتك ذات الصلة',
    'appraiserApply.previousEmployers': 'أصحاب العمل السابقون',
    'appraiserApply.previousEmployersPlaceholder': 'اذكر أصحاب العمل السابقين في صناعة الساعات الفاخرة أو المجوهرات',
    'appraiserApply.references': 'المراجع المهنية',
    'appraiserApply.referencesPlaceholder': 'قدم معلومات الاتصال للمراجع المهنية',
    'appraiserApply.coverLetter': 'خطاب التغطية',
    'appraiserApply.coverLetterPlaceholder': 'أخبرنا لماذا ترغب في الانضمام إلى فريقنا وما الذي يجعلك مقيّماً رائعاً',
    'appraiserApply.submitting': 'جاري التقديم...',
    'appraiserApply.submit': 'تقديم الطلب',
    'appraiserApply.cancel': 'إلغاء',
    'appraiserApply.signInError': 'يرجى تسجيل الدخول للتقديم',
    'appraiserApply.specializationError': 'يرجى اختيار تخصص واحد على الأقل',
    'appraiserApply.success': 'تم تقديم الطلب بنجاح!',
    'appraiserApply.error': 'فشل في تقديم الطلب',
    // Admin Create Auction
    'adminCreateAuction.createNewAuction': 'إنشاء مزاد جديد',
    'adminCreateAuction.editScheduledAuction': 'تعديل المزاد المجدول',
    'adminCreateAuction.createDescription': 'إنشاء مزاد معتمد ونشط مباشرة',
    'adminCreateAuction.editDescription': 'تحديث تفاصيل المزاد قبل بدء البث المباشر',
    'adminCreateAuction.basicInformation': 'المعلومات الأساسية',
    'adminCreateAuction.title': 'العنوان',
    'adminCreateAuction.titlePlaceholder': 'مثال: ساعة رولكس سبمارينر كلاسيكية',
    'adminCreateAuction.category': 'الفئة',
    'adminCreateAuction.selectCategory': 'اختر فئة',
    'adminCreateAuction.watches': 'ساعات',
    'adminCreateAuction.jewelry': 'مجوهرات',
    'adminCreateAuction.diamonds': 'ألماس',
    'adminCreateAuction.luxuryItems': 'أغراض فاخرة',
    'adminCreateAuction.description': 'الوصف',
    'adminCreateAuction.descriptionPlaceholder': 'وصف تفصيلي للقطعة...',
    'adminCreateAuction.schedulingPricing': 'الجدولة والتسعير',
    'adminCreateAuction.schedulingNote': 'حدد وقت بدء مستقبلي لجدولة المزاد. سيبدأ تلقائياً في الوقت المحدد.',
    'adminCreateAuction.startingPrice': 'السعر الابتدائي ($)',
    'adminCreateAuction.startingPricePlaceholder': 'مثال: 5000',
    'adminCreateAuction.minimumIncrement': 'الحد الأدنى للزيادة ($)',
    'adminCreateAuction.minimumIncrementPlaceholder': 'مثال: 100',
    'adminCreateAuction.startTime': 'وقت البدء',
    'adminCreateAuction.endTime': 'وقت الانتهاء',
    'adminCreateAuction.images': 'الصور',
    'adminCreateAuction.imagesNote': 'ارفع حتى 5 صور (الصورة الأولى ستكون الرئيسية)',
    'adminCreateAuction.clickToUpload': 'انقر لرفع الصور (الحد الأقصى 5)',
    'adminCreateAuction.mainImage': 'الصورة الرئيسية',
    'adminCreateAuction.specifications': 'المواصفات',
    'adminCreateAuction.addSpecification': 'إضافة مواصفة',
    'adminCreateAuction.labelPlaceholder': 'التسمية (مثال: العلامة التجارية)',
    'adminCreateAuction.valuePlaceholder': 'القيمة (مثال: رولكس)',
    'adminCreateAuction.certificates': 'الشهادات',
    'adminCreateAuction.addCertificate': 'إضافة شهادة',
    'adminCreateAuction.certificateNamePlaceholder': 'اسم الشهادة',
    'adminCreateAuction.issuerPlaceholder': 'الجهة المصدرة',
    'adminCreateAuction.createAuction': 'إنشاء المزاد',
    'adminCreateAuction.updateAuction': 'تحديث المزاد',
    'adminCreateAuction.creatingAuction': 'جارٍ إنشاء المزاد...',
    'adminCreateAuction.updatingAuction': 'جارٍ تحديث المزاد...',
    'adminCreateAuction.cancel': 'إلغاء',
    'adminCreateAuction.maxImagesError': 'الحد الأقصى 5 صور',
    'adminCreateAuction.endTimeError': 'يجب أن يكون وقت الانتهاء بعد وقت البدء',
    'adminCreateAuction.uploadImageError': 'يرجى رفع صورة واحدة على الأقل',
    'adminCreateAuction.onlyScheduledEditable': 'يمكن تعديل المزادات المجدولة فقط',
    'adminCreateAuction.loadAuctionError': 'فشل في تحميل بيانات المزاد',
    'adminCreateAuction.auctionUpdatedScheduled': 'تم تحديث المزاد! سيبدأ البث المباشر في',
    'adminCreateAuction.auctionUpdatedLive': 'تم تحديث المزاد بنجاح وهو نشط الآن!',
    'adminCreateAuction.auctionScheduled': 'تمت جدولة المزاد بنجاح! سيبدأ البث المباشر في',
    'adminCreateAuction.auctionCreatedLive': 'تم إنشاء المزاد بنجاح وهو نشط الآن!',
    'adminCreateAuction.createError': 'فشل في إنشاء المزاد',
    // Process Steps
    'process.badge': 'كيف يعمل',
    'process.title': '١ ← ٢ ← ٣ ← ٤ ← ٥',
    'process.subtitle': 'من التقديم إلى الدفع، نتعامل مع كل شيء بعناية وخبرة',
    'process.stepLabel': 'الخطوة',
    'process.step1.title': 'املأ النموذج',
    'process.step1.description': 'ابدأ رحلتك بإكمال نموذج التقديم البسيط عبر الإنترنت. قدم تفاصيل عن قطعتك الفاخرة بما في ذلك الصور والحالة وأي وثائق.',
    'process.step1.detail1': 'أكمل نموذج التقديم الآمن عبر الإنترنت مع تفاصيل القطعة',
    'process.step1.detail2': 'حمّل صوراً عالية الجودة من زوايا متعددة',
    'process.step1.detail3': 'أرفق الشهادات والتقييمات أو وثائق المصدر',
    'process.step2.title': 'جدولة الشحن',
    'process.step2.description': 'بمجرد الموافقة، ننسق الشحن الآمن والمؤمن إلى منشأتنا. قطعتك محمية في كل خطوة.',
    'process.step2.detail1': 'استلم ملصق شحن مدفوع مسبقاً ومؤمن بالكامل',
    'process.step2.detail2': 'إرشادات التغليف الاحترافية مقدمة',
    'process.step2.detail3': 'تتبع في الوقت الفعلي من الاستلام إلى التسليم',
    'process.step3.title': 'التحضير للبيع',
    'process.step3.description': 'يقوم فريقنا الخبير بتصوير قطعتك بشكل احترافي وتوثيقها وفهرستها لتحقيق أقصى اهتمام وقيمة للمشترين.',
    'process.step3.detail1': 'تصوير احترافي في استوديو خاص',
    'process.step3.detail2': 'توثيق وتصنيف من الخبراء',
    'process.step3.detail3': 'كتابة وصف جذاب من المتخصصين',
    'process.step4.title': 'المزاد عبر الإنترنت',
    'process.step4.description': 'تُعرض قطعتك على شبكتنا العالمية من المشترين المؤهلين. شاهد العروض تأتي وقطعتك تجد منزلها الجديد.',
    'process.step4.detail1': 'عرض لآلاف هواة الجمع المعتمدين',
    'process.step4.detail2': 'مزايدة في الوقت الفعلي مع تحديثات مباشرة',
    'process.step4.detail3': 'دعم مخصص طوال المزاد',
    'process.step5.title': 'احصل على المال',
    'process.step5.description': 'بمجرد البيع، احصل على دفع سريع وآمن. عمليتنا الشفافة تضمن حصولك على المال بسرعة بدون رسوم خفية.',
    'process.step5.detail1': 'دفع سريع خلال 7 أيام عمل من البيع',
    'process.step5.detail2': 'خيارات دفع متعددة بما في ذلك التحويل البنكي',
    'process.step5.detail3': 'تقرير معاملة مفصل لسجلاتك',
    'process.cta': 'ادخل المزاد الإلكتروني اليوم.',
    'process.ctaSubtext': 'قدم قطعتك الفاخرة وابدأ رحلة المزاد الخاصة بك',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.about': 'À propos',
    'nav.buyers': 'Acheteurs',
    'nav.sellers': 'Vendeurs',
    'nav.browseAuctions': 'Parcourir les enchères',
    'nav.auctions': 'Enchères',
    'nav.contact': 'Contact',
    'hero.title': 'CROWN AUCTIONS',
    'hero.subtitle': 'Stock de détail excédentaire et liquidations de nombreux revendeurs agréés',
    'hero.cta': 'Commencer Aujourd\'hui',
    'hero.howItWorks': 'Comment ça marche',
    'hero.step1.title': 'PARLEZ-NOUS DE VOS ARTICLES',
    'hero.step1.desc': 'Incluez des photos et tous les documents ou certificats pertinents. Des informations détaillées amélioreront notre niveau de service.',
    'hero.step2.title': 'PLANIFIEZ UNE VISITE',
    'hero.step2.desc': 'Sélectionnez une date et une heure pour rencontrer notre expert en privé. Recevez une évaluation gratuite de vos articles sans obligation de vendre.',
    'hero.step3.title': 'RENCONTREZ UN EXPERT POUR RECEVOIR UNE OFFRE',
    'hero.step3.desc': 'Après examen de vos articles, nous vous fournirons une offre d\'achat. Il n\'y a pas de frais ni de commissions pour notre service.',
    'hero.step4.title': 'SOYEZ PAYÉ',
    'hero.step4.desc': 'Recevez un paiement immédiat par virement bancaire.',
    'itemCategory.title': 'Quel type d\'article avez-vous?',
    'itemCategory.subtitle': 'Sélectionnez la catégorie qui décrit le mieux votre article',
    'itemCategory.diamonds': 'Diamants',
    'itemCategory.diamondsDesc': 'Diamants en vrac et pierres certifiées',
    'itemCategory.watches': 'Montres',
    'itemCategory.watchesDesc': 'Montres de luxe et suisses',
    'itemCategory.jewelry': 'Bijoux',
    'itemCategory.jewelryDesc': 'Colliers, bracelets et boucles d\'oreilles',
    'itemCategory.rings': 'Bagues',
    'itemCategory.ringsDesc': 'Bagues de fiançailles et de mariage',
    'itemCategory.luxury': 'Articles de Luxe',
    'itemCategory.luxuryDesc': 'Pièces de créateurs et de collection',
    'itemCategory.other': 'Autre',
    'itemCategory.otherDesc': 'Autres objets de valeur',
    'itemCategory.hint': 'Nos experts vous aideront à déterminer la meilleure catégorie pour votre article',
    'about.title': 'À propos de Crown Auctions',
    'about.description': "Crown Auctions est une maison de ventes aux enchères de luxe de premier plan, spécialisée dans les bijoux fins, les diamants et les montres suisses. Avec des décennies d'expertise, nous connectons les acheteurs exigeants avec des pièces exceptionnelles.",
    'about.history.title': 'Notre Histoire',
    'about.history.content': "Fondée en 1985, Crown Auctions a commencé comme une petite entreprise familiale de bijouterie à Sydney. Pendant près de quatre décennies, nous sommes devenus l'une des maisons de ventes aux enchères les plus respectées de la région Asie-Pacifique. La passion de nos fondateurs pour les montres exquises et les bijoux fins s'est transmise de génération en génération, maintenant le même engagement envers la qualité et l'authenticité qui a défini nos premiers jours.",
    'about.mission.title': 'Notre Mission',
    'about.mission.content': "Fournir une plateforme fiable, transparente et prestigieuse où les collectionneurs et passionnés peuvent découvrir, acquérir et vendre les plus beaux articles de luxe du monde avec une confiance totale et un service exceptionnel.",
    'about.team.title': "Équipe de Direction",
    'about.team.member1.name': 'James Richardson',
    'about.team.member1.role': 'Directeur Général',
    'about.team.member2.name': 'Sarah Chen',
    'about.team.member2.role': "Responsable de l'Authentification",
    'about.team.member3.name': 'Michael Torres',
    'about.team.member3.role': 'Directeur des Enchères',
    'about.values.title': 'Nos Valeurs Fondamentales',
    'about.values.value1': 'Intégrité et Confiance',
    'about.values.value2': 'Excellence et Qualité',
    'about.values.value3': 'Service Client Prioritaire',
    'about.stats.years': '38+',
    'about.stats.yearsLabel': "Années d'Excellence",
    'about.stats.auctions': '15K+',
    'about.stats.auctionsLabel': 'Enchères Réussies',
    'about.stats.countries': '45+',
    'about.stats.countriesLabel': 'Pays Desservis',
    'about.stats.clients': '50K+',
    'about.stats.clientsLabel': 'Clients Satisfaits',
    'about.contact.title': 'Contactez-Nous',
    'about.contact.description': 'Vous avez des questions sur nos enchères ou services? Nous serions ravis de vous entendre.',
    'about.contact.name': 'Votre Nom',
    'about.contact.email': 'Adresse Email',
    'about.contact.subject': 'Sujet',
    'about.contact.message': 'Votre Message',
    'about.contact.send': 'Envoyer le Message',
    'about.contact.sending': 'Envoi en cours...',
    'about.contact.success': 'Votre message a été envoyé avec succès! Nous vous répondrons bientôt.',
    'about.contact.error': "Échec de l'envoi du message. Veuillez réessayer.",
    'about.contact.loginRequired': 'Veuillez vous connecter pour envoyer un message.',
    'about.contact.subjectGeneral': 'Demande Générale',
    'about.contact.subjectAuction': 'Question sur une Enchère',
    'about.contact.subjectSelling': 'Vendre un Article',
    'about.contact.subjectAppraisal': "Demande d'Évaluation",
    'about.footer.contactInfo': 'Coordonnées',
    'about.footer.followUs': 'Suivez-nous',
    'about.footer.address': 'Pearl Tower, West Bay, Doha, Qatar',
    'about.footer.businessHours': 'Heures d\'ouverture',
    'about.footer.weekdays': 'Dimanche - Jeudi: 9h00 - 18h00',
    'about.footer.saturday': 'Vendredi: 14h00 - 18h00',
    'about.footer.sunday': 'Samedi: Fermé',
    'about.footer.liveChat': 'Chat en direct',
    'about.footer.chatOnline': 'Nous sommes en ligne',
    'about.footer.chatHours': 'Disponible pendant les heures d\'ouverture',
    'about.trustpilot.excellent': 'Excellent',
    'about.trustpilot.reviews': '2 847 avis',
    'features.trusted.title': 'Confiance mondiale',
    'features.trusted.description': 'Nous sommes une société enregistrée détenant une licence conforme à toutes les lois commerciales australiennes, systèmes d\'audit et pratiques de commerce équitable en vertu de la loi sur les commissaires-priseurs 2014.',
    'features.expert.title': 'Conseils d\'experts',
    'features.expert.description': 'Nous offrons des conseils d\'experts et des services d\'évaluation pour vous aider à connaître la valeur correcte de vos articles. Contactez-nous pour des évaluations et conseils professionnels.',
    'features.premium.title': 'Sélection Premium',
    'features.premium.description': 'Diamants certifiés GIA, bijoux fins et montres suisses de grandes marques. Obtenez vos articles désirés à des valeurs exceptionnelles, bien en dessous des prix de détail.',
    'footer.quickLinks': 'Liens rapides',
    'footer.services': 'Services',
    'footer.contact': 'Contact',
    'footer.copyright': 'Crown Auctions. Tous droits réservés. Licencié sous la loi sur les commissaires-priseurs 2014.',
    'featured.title': 'Enchères en vedette',
    'featured.subtitle': 'Parcourez nos enchères en direct et placez vos offres',
    'featured.all': 'Tout',
    'featured.jewellery': 'Bijoux',
    'featured.watches': 'Montres',
    'featured.diamonds': 'Diamants',
    'featured.noAuctions': 'Aucune enchère trouvée dans cette catégorie. Revenez bientôt !',
    'auction.1.title': 'Bague solitaire diamant platine - 2,5 carats',
    'auction.2.title': 'Montre chronographe suisse - Bracelet cuir noir',
    'auction.3.title': 'Collier pendentif or 18K avec diamant',
    'auction.4.title': 'Rolex Datejust vintage - Or 18K',
    'auction.5.title': 'Boucles d\'oreilles saphir et diamant - Or blanc',
    'auction.6.title': 'Diamant en vrac certifié GIA 3,2 carats - VS1',
    'auction.startingPrice': 'Prix de départ',
    'auction.currentBid': 'Enchère actuelle',
    'auction.bids': 'enchères',
    'auction.timeLeft': 'Temps restant',
    'auction.active': 'Actif',
    'auction.paused': 'En pause',
    // Admin Dashboard
    'admin.title': 'Tableau de bord administrateur',
    'admin.subtitle': 'Gérer et examiner les soumissions d\'enchères',
    'admin.createAuction': 'Créer une nouvelle enchère',
    'admin.pendingReview': 'En attente de révision',
    'admin.approved': 'Approuvé pour Vente/Enchère',
    'admin.scheduled': 'Programmé',
    'admin.rejected': 'Rejeté',
    'admin.pending': 'En attente',
    'admin.appraisers': 'Évaluateurs',
    'admin.noPending': 'Aucune enchère en attente',
    'admin.noScheduled': 'Aucune enchère programmée',
    'admin.noApproved': 'Aucune enchère approuvée',
    'admin.noRejected': 'Aucune enchère rejetée',
    'admin.noAppraisers': 'Aucune candidature d\'évaluateur pour le moment',
    'admin.category': 'Catégorie',
    'admin.startingPrice': 'Prix de départ',
    'admin.currentBid': 'Enchère actuelle',
    'admin.scheduledStart': 'Début programmé',
    'admin.submitted': 'Soumis',
    'admin.rejectionReason': 'Raison du rejet',
    'admin.resubmission': 'Nouvelle soumission',
    'admin.saveComment': 'Enregistrer le commentaire',
    'admin.saving': 'Enregistrement...',
    'admin.viewDetails': 'Voir les détails',
    'admin.edit': 'Modifier',
    'admin.approve': 'Approuver',
    'admin.reject': 'Rejeter',
    'admin.pauseAuction': 'Mettre en pause',
    'admin.resumeAuction': 'Reprendre l\'enchère',
    'admin.startAuction': 'Démarrer l\'enchère',
    'admin.live': 'En direct',
    'admin.rejectDialog.title': 'Rejeter l\'enchère',
    'admin.rejectDialog.description': 'Veuillez fournir une raison pour rejeter cette enchère. Cela sera visible par le soumissionnaire.',
    'admin.rejectDialog.placeholder': 'Entrez la raison du rejet...',
    'admin.rejectDialog.cancel': 'Annuler',
    'admin.rejectDialog.rejecting': 'Rejet en cours...',
    'admin.rejectDialog.confirm': 'Rejeter l\'enchère',
    // Appraiser section
    'admin.appraiser.email': 'Email',
    'admin.appraiser.phone': 'Téléphone',
    'admin.appraiser.experience': 'Expérience',
    'admin.appraiser.years': 'ans',
    'admin.appraiser.applied': 'Candidature déposée',
    'admin.appraiser.specializations': 'Spécialisations',
    'admin.appraiser.certifications': 'Certifications',
    'admin.appraiser.previousEmployers': 'Employeurs précédents',
    'admin.appraiser.references': 'Références professionnelles',
    'admin.appraiser.coverLetter': 'Lettre de motivation',
    'admin.appraiser.adminNotes': 'Notes administrateur',
    'admin.appraiser.notesPlaceholder': 'Ajouter des notes sur cette candidature...',
    'admin.appraiser.reviewedOn': 'Examiné le',
    // Submit Auction
    'submit.title': 'Soumettre un article aux enchères',
    'submit.description': 'Soumettez votre article de luxe pour approbation. Toutes les soumissions sont examinées par notre équipe.',
    'submit.prefilled': 'Formulaire pré-rempli avec les données de votre précédente soumission',
    'submit.basicInfo': 'Informations de base',
    'submit.itemTitle': 'Titre',
    'submit.titlePlaceholder': 'ex: Rolex Submariner 116610LN',
    'submit.category': 'Catégorie',
    'submit.selectCategory': 'Sélectionner une catégorie',
    'submit.watches': 'Montres',
    'submit.jewelry': 'Bijoux',
    'submit.diamonds': 'Diamants',
    'submit.luxuryGoods': 'Articles de luxe',
    'submit.itemDescription': 'Description',
    'submit.descriptionPlaceholder': 'Description détaillée de l\'article, incluant l\'état, la provenance et les caractéristiques notables...',
    'submit.minChars': 'Minimum 20 caractères',
    'submit.pricing': 'Prix',
    'submit.startingPrice': 'Prix de départ (USD)',
    'submit.minIncrement': 'Incrément minimum d\'enchère (USD)',
    'submit.endDateTime': 'Date et heure de fin de l\'enchère',
    'submit.images': 'Images',
    'submit.imagesHelp': 'Téléchargez des images de haute qualité (max 10 images, 5 Mo chacune, JPG/PNG/WEBP)',
    'submit.upload': 'Télécharger',
    'submit.specifications': 'Spécifications (optionnel)',
    'submit.specLabel': 'Libellé (ex: Marque)',
    'submit.specValue': 'Valeur (ex: Rolex)',
    'submit.certificates': 'Certificats (optionnel)',
    'submit.certName': 'Nom du certificat',
    'submit.certIssuer': 'Émetteur',
    'submit.add': 'Ajouter',
    'submit.submitting': 'Soumission en cours...',
    'submit.submitForApproval': 'Soumettre pour approbation',
    'submit.cancel': 'Annuler',
    // Testimonials
    'testimonials.title': 'Ce que disent nos clients',
    'testimonials.1.text': 'Quelle belle sélection, j\'ai acheté 2 articles et j\'étais très satisfait. Merci !',
    'testimonials.1.author': 'Sarah M.',
    'testimonials.2.text': 'Service professionnel et articles de luxe authentiques. Le processus d\'authentification m\'a donné une confiance totale dans mon achat.',
    'testimonials.2.author': 'James R.',
    'testimonials.3.text': 'J\'achète chez Crown Auctions depuis des années. Leur collection de montres suisses est inégalée et les prix sont exceptionnels.',
    'testimonials.3.author': 'Michael K.',
    // Footer
    'footer.tagline': 'Spécialisé dans les enchères de bijoux fins, diamants et montres suisses',
    'footer.buyers': 'Acheteurs',
    'footer.sellers': 'Vendeurs',
    'footer.browseAuctions': 'Parcourir les enchères',
    'footer.valuationServices': 'Services d\'évaluation',
    'footer.sellWithUs': 'Vendre avec nous',
    'footer.authentication': 'Authentification',
    'footer.becomeAppraiser': 'Devenir évaluateur',
    'footer.email': 'Email',
    'footer.phone': 'Téléphone',
    'footer.licensedAuctioneer': 'Commissaire-priseur agréé',
    // Dashboard
    'dashboard.signOut': 'Déconnexion',
    'dashboard.profile': 'Profil',
    'dashboard.mySubmissions': 'Mes soumissions',
    'dashboard.watchlist': 'Liste de suivi',
    'dashboard.myBids': 'Mes enchères',
    'dashboard.profileInfo': 'Informations du profil',
    'dashboard.updateDetails': 'Mettez à jour vos informations personnelles',
    'dashboard.fullName': 'Nom complet',
    'dashboard.email': 'Email',
    'dashboard.phone': 'Téléphone',
    'dashboard.updating': 'Mise à jour...',
    'dashboard.updateProfile': 'Mettre à jour le profil',
    'dashboard.noSubmissions': 'Aucune soumission d\'enchère pour le moment',
    'dashboard.submitFirst': 'Soumettre votre premier article',
    'dashboard.pendingReview': 'En attente de révision',
    'dashboard.pending': 'En attente',
    'dashboard.resubmission': 'Nouvelle soumission',
    'dashboard.startingPrice': 'Prix de départ',
    'dashboard.submitted': 'Soumis',
    'dashboard.pendingMessage': 'Votre soumission est en cours d\'examen par notre équipe. Vous recevrez un email une fois traitée.',
    'dashboard.withdrawing': 'Retrait en cours...',
    'dashboard.withdrawSubmission': 'Retirer la soumission',
    'dashboard.approvedLive': 'Approuvé et en direct',
    'dashboard.live': 'En direct',
    'dashboard.currentBid': 'Enchère actuelle',
    'dashboard.approved': 'Approuvé',
    'dashboard.ends': 'Se termine',
    'dashboard.viewAuction': 'Voir l\'enchère',
    'dashboard.notApproved': 'Non approuvé',
    'dashboard.rejected': 'Rejeté',
    'dashboard.rejectionReason': 'Raison du rejet',
    'dashboard.submitAnother': 'Soumettre un autre article',
    'dashboard.noSavedAuctions': 'Aucune enchère sauvegardée pour le moment',
    'dashboard.browseAuctions': 'Parcourir les enchères',
    'dashboard.savedOn': 'Sauvegardé le',
    'dashboard.remove': 'Supprimer',
    'dashboard.noActiveBids': 'Aucune enchère active',
    'dashboard.winning': 'Gagnant',
    'dashboard.outbid': 'Surenchéri',
    'dashboard.yourHighestBid': 'Votre enchère la plus élevée',
    'dashboard.currentHighest': 'Plus haute actuelle',
    'dashboard.lastBid': 'Dernière enchère',
    'dashboard.bidsPlaced': 'enchères placées',
    'dashboard.view': 'Voir',
    'dashboard.rebidNow': 'Renchérir maintenant',
    'dashboard.user': 'Utilisateur',
    'dashboard.auction': 'Enchère',
    // Auction Detail
    'auctionDetail.backToAuctions': 'Retour aux enchères',
    'auctionDetail.notFound': 'Enchère introuvable',
    'auctionDetail.returnHome': 'Retour à l\'accueil',
    'auctionDetail.startingPrice': 'Prix de départ',
    'auctionDetail.currentBid': 'Enchère actuelle',
    'auctionDetail.bidPlaced': 'enchère placée',
    'auctionDetail.bidsPlaced': 'enchères placées',
    'auctionDetail.endsIn': 'Se termine dans',
    'auctionDetail.placeYourBid': 'Placez votre enchère',
    'auctionDetail.auctionPaused': 'Enchère en pause',
    'auctionDetail.auctionPausedMessage': 'Cette enchère a été temporairement mise en pause par les administrateurs. Les enchères sont actuellement désactivées.',
    'auctionDetail.adminCannotBid': 'Les administrateurs ne peuvent pas enchérir pour maintenir l\'intégrité de l\'enchère et éviter les conflits d\'intérêts.',
    'auctionDetail.yourBidAmount': 'Votre montant d\'enchère (AUD)',
    'auctionDetail.minimumBid': 'Enchère minimum',
    'auctionDetail.increment': 'incrément',
    'auctionDetail.quickBid': 'Enchère rapide',
    'auctionDetail.minBid': 'Enchère min',
    'auctionDetail.placeBid': 'Placer l\'enchère',
    'auctionDetail.biddingDisabled': 'Enchères désactivées',
    'auctionDetail.specifications': 'Spécifications',
    'auctionDetail.authentication': 'Authentification et certificats',
    'auctionDetail.issuedBy': 'Délivré par',
    'auctionDetail.bidHistory': 'Historique des enchères',
    'auctionDetail.loadingBidHistory': 'Chargement de l\'historique des enchères...',
    'auctionDetail.noBidsYet': 'Aucune enchère placée pour le moment. Soyez le premier à enchérir !',
    'auctionDetail.bidder': 'Enchérisseur',
    'auctionDetail.bidAmount': 'Montant de l\'enchère',
    'auctionDetail.time': 'Heure',
    'auctionDetail.you': 'Vous',
    'auctionDetail.highest': 'Plus haute',
    'auctionDetail.signInRequired': 'Connexion requise',
    'auctionDetail.signInToBid': 'Veuillez vous connecter pour enchérir.',
    'auctionDetail.invalidBid': 'Enchère invalide',
    'auctionDetail.enterValidBid': 'Veuillez entrer un montant d\'enchère valide.',
    'auctionDetail.description': 'Description',
    // Certificate names
    'cert.giaReport': 'Rapport diamant GIA',
    'cert.platinumHallmark': 'Poinçon platine',
    'cert.swissMade': 'Certificat Swiss Made',
    'cert.warranty': 'Carte de garantie',
    'cert.goldAssay': 'Certificat d\'essai d\'or',
    'cert.authenticityReport': 'Rapport d\'authenticité',
    'cert.appraisalReport': 'Rapport d\'évaluation',
    'cert.insuranceValuation': 'Évaluation d\'assurance',
    // Certificate issuers
    'cert.issuer.gia': 'Institut Gemmologique d\'Amérique',
    'cert.issuer.australianAssay': 'Bureau d\'essai australien',
    'cert.issuer.swissWatch': 'Fédération de l\'industrie horlogère suisse',
    'cert.issuer.manufacturer': 'Fabricant',
    'cert.issuer.igi': 'Institut Gemmologique International',
    'cert.issuer.hrd': 'HRD Anvers',
    // Categories
    'category.watches': 'Montres',
    'category.jewellery': 'Bijoux',
    'category.diamonds': 'Diamants',
    'category.rings': 'Bagues',
    'category.necklaces': 'Colliers',
    'category.bracelets': 'Bracelets',
    'category.earrings': 'Boucles d\'oreilles',
    'category.other': 'Autre',
    // Specifications
    'specs.title': 'Spécifications',
    'specs.basicInfo': 'Informations de base',
    'specs.caliber': 'Calibre',
    'specs.case': 'Boîtier',
    'specs.braceletStrap': 'Bracelet/Sangle',
    'specs.functions': 'Fonctions',
    'specs.otherDetails': 'Autres détails',
    'specs.conditionVerified': 'État vérifié',
    'specs.conditionMessage': 'Cet article a été inspecté et authentifié par notre équipe d\'experts. Toutes les spécifications ont été vérifiées pour leur exactitude.',
    'specs.productSafety': 'Sécurité du produit',
    'specs.showInfo': 'Afficher les informations',
    // Spec Labels
    'spec.brand': 'Marque',
    'spec.model': 'Modèle',
    'spec.referenceNumber': 'Numéro de référence',
    'spec.yearOfProduction': 'Année de production',
    'spec.condition': 'État',
    'spec.scopeOfDelivery': 'Contenu de la livraison',
    'spec.gender': 'Genre',
    'spec.location': 'Emplacement',
    'spec.movement': 'Mouvement',
    'spec.caliber': 'Calibre',
    'spec.powerReserve': 'Réserve de marche',
    'spec.numberOfJewels': 'Nombre de rubis',
    'spec.caseMaterial': 'Matériau du boîtier',
    'spec.caseDiameter': 'Diamètre du boîtier',
    'spec.caseThickness': 'Épaisseur du boîtier',
    'spec.waterResistance': 'Étanchéité',
    'spec.bezelMaterial': 'Matériau de la lunette',
    'spec.crystal': 'Verre',
    'spec.dial': 'Cadran',
    'spec.dialNumerals': 'Index du cadran',
    'spec.braceletMaterial': 'Matériau du bracelet',
    'spec.braceletColor': 'Couleur du bracelet',
    'spec.clasp': 'Fermoir',
    'spec.claspMaterial': 'Matériau du fermoir',
    'spec.chronograph': 'Chronographe',
    'spec.dateDisplay': 'Affichage de la date',
    'spec.listingCode': 'Code de référence',
    'spec.metal': 'Métal',
    'spec.diamondWeight': 'Poids du diamant',
    'spec.colorGrade': 'Grade de couleur',
    'spec.clarity': 'Pureté',
    'spec.cut': 'Taille',
    'spec.ringSize': 'Taille de bague',
    'spec.caratWeight': 'Poids en carats',
    'spec.shape': 'Forme',
    'spec.polish': 'Polissage',
    'spec.symmetry': 'Symétrie',
    'spec.fluorescence': 'Fluorescence',
    'spec.chainLength': 'Longueur de chaîne',
    'spec.pendantSize': 'Taille du pendentif',
    'spec.claspType': 'Type de fermoir',
    'spec.totalDiamondWeight': 'Poids total des diamants',
    'spec.diamondQuality': 'Qualité du diamant',
    'spec.sapphireWeight': 'Poids du saphir',
    'spec.sapphireOrigin': 'Origine du saphir',
    'spec.earringLength': 'Longueur des boucles',
    'spec.closureType': 'Type de fermeture',
    // Appraiser Apply Form
    'appraiserApply.title': 'Postuler comme évaluateur de montres',
    'appraiserApply.subtitle': 'Rejoignez notre équipe d\'évaluateurs experts et aidez à authentifier les montres de luxe',
    'appraiserApply.fullName': 'Nom complet',
    'appraiserApply.email': 'Email',
    'appraiserApply.phone': 'Numéro de téléphone',
    'appraiserApply.experience': 'Années d\'expérience',
    'appraiserApply.specializations': 'Spécialisations',
    'appraiserApply.luxuryWatches': 'Montres de luxe',
    'appraiserApply.fineJewelry': 'Bijoux fins',
    'appraiserApply.diamonds': 'Diamants',
    'appraiserApply.vintageTimepieces': 'Montres vintage',
    'appraiserApply.estateJewelry': 'Bijoux de succession',
    'appraiserApply.designerPieces': 'Pièces de créateurs',
    'appraiserApply.certifications': 'Certifications et qualifications',
    'appraiserApply.certificationsPlaceholder': 'Listez vos certifications, diplômes et qualifications pertinents',
    'appraiserApply.previousEmployers': 'Employeurs précédents',
    'appraiserApply.previousEmployersPlaceholder': 'Listez vos employeurs précédents dans l\'industrie des montres de luxe ou de la bijouterie',
    'appraiserApply.references': 'Références professionnelles',
    'appraiserApply.referencesPlaceholder': 'Fournissez les coordonnées de vos références professionnelles',
    'appraiserApply.coverLetter': 'Lettre de motivation',
    'appraiserApply.coverLetterPlaceholder': 'Dites-nous pourquoi vous souhaitez rejoindre notre équipe et ce qui fait de vous un excellent évaluateur',
    'appraiserApply.submitting': 'Soumission en cours...',
    'appraiserApply.submit': 'Soumettre la candidature',
    'appraiserApply.cancel': 'Annuler',
    'appraiserApply.signInError': 'Veuillez vous connecter pour postuler',
    'appraiserApply.specializationError': 'Veuillez sélectionner au moins une spécialisation',
    'appraiserApply.success': 'Candidature soumise avec succès !',
    'appraiserApply.error': 'Échec de la soumission de la candidature',
    // Admin Create Auction
    'adminCreateAuction.createNewAuction': 'Créer une nouvelle enchère',
    'adminCreateAuction.editScheduledAuction': 'Modifier l\'enchère programmée',
    'adminCreateAuction.createDescription': 'Créer une enchère directement approuvée et active',
    'adminCreateAuction.editDescription': 'Mettre à jour les détails de l\'enchère avant sa mise en ligne',
    'adminCreateAuction.basicInformation': 'Informations de base',
    'adminCreateAuction.title': 'Titre',
    'adminCreateAuction.titlePlaceholder': 'ex., Rolex Submariner Vintage',
    'adminCreateAuction.category': 'Catégorie',
    'adminCreateAuction.selectCategory': 'Sélectionner une catégorie',
    'adminCreateAuction.watches': 'Montres',
    'adminCreateAuction.jewelry': 'Bijoux',
    'adminCreateAuction.diamonds': 'Diamants',
    'adminCreateAuction.luxuryItems': 'Articles de luxe',
    'adminCreateAuction.description': 'Description',
    'adminCreateAuction.descriptionPlaceholder': 'Description détaillée de l\'article...',
    'adminCreateAuction.schedulingPricing': 'Programmation et tarification',
    'adminCreateAuction.schedulingNote': 'Définissez une heure de début future pour programmer l\'enchère. Elle démarrera automatiquement à l\'heure spécifiée.',
    'adminCreateAuction.startingPrice': 'Prix de départ ($)',
    'adminCreateAuction.startingPricePlaceholder': 'ex., 5000',
    'adminCreateAuction.minimumIncrement': 'Incrément minimum ($)',
    'adminCreateAuction.minimumIncrementPlaceholder': 'ex., 100',
    'adminCreateAuction.startTime': 'Heure de début',
    'adminCreateAuction.endTime': 'Heure de fin',
    'adminCreateAuction.images': 'Images',
    'adminCreateAuction.imagesNote': 'Téléchargez jusqu\'à 5 images (la première sera l\'image principale)',
    'adminCreateAuction.clickToUpload': 'Cliquez pour télécharger des images (Max 5)',
    'adminCreateAuction.mainImage': 'Image principale',
    'adminCreateAuction.specifications': 'Spécifications',
    'adminCreateAuction.addSpecification': 'Ajouter une spécification',
    'adminCreateAuction.labelPlaceholder': 'Libellé (ex., Marque)',
    'adminCreateAuction.valuePlaceholder': 'Valeur (ex., Rolex)',
    'adminCreateAuction.certificates': 'Certificats',
    'adminCreateAuction.addCertificate': 'Ajouter un certificat',
    'adminCreateAuction.certificateNamePlaceholder': 'Nom du certificat',
    'adminCreateAuction.issuerPlaceholder': 'Émetteur',
    'adminCreateAuction.createAuction': 'Créer l\'enchère',
    'adminCreateAuction.updateAuction': 'Mettre à jour l\'enchère',
    'adminCreateAuction.creatingAuction': 'Création de l\'enchère...',
    'adminCreateAuction.updatingAuction': 'Mise à jour de l\'enchère...',
    'adminCreateAuction.cancel': 'Annuler',
    'adminCreateAuction.maxImagesError': 'Maximum 5 images autorisées',
    'adminCreateAuction.endTimeError': 'L\'heure de fin doit être après l\'heure de début',
    'adminCreateAuction.uploadImageError': 'Veuillez télécharger au moins une image',
    'adminCreateAuction.onlyScheduledEditable': 'Seules les enchères programmées peuvent être modifiées',
    'adminCreateAuction.loadAuctionError': 'Échec du chargement des données de l\'enchère',
    'adminCreateAuction.auctionUpdatedScheduled': 'Enchère mise à jour! Elle sera en ligne à',
    'adminCreateAuction.auctionUpdatedLive': 'Enchère mise à jour avec succès et maintenant en ligne!',
    'adminCreateAuction.auctionScheduled': 'Enchère programmée avec succès! Elle sera en ligne à',
    'adminCreateAuction.auctionCreatedLive': 'Enchère créée avec succès et maintenant en ligne!',
    'adminCreateAuction.createError': 'Échec de la création de l\'enchère',
    // Process Steps
    'process.badge': 'Comment ça marche',
    'process.title': '1 → 2 → 3 → 4 → 5',
    'process.subtitle': 'De la soumission au paiement, nous gérons tout avec soin et expertise',
    'process.stepLabel': 'ÉTAPE',
    'process.step1.title': 'Remplir le formulaire',
    'process.step1.description': 'Commencez votre parcours en remplissant notre simple formulaire de soumission en ligne. Fournissez des détails sur votre article de luxe, y compris photos, état et documentation.',
    'process.step1.detail1': 'Remplissez le formulaire de soumission sécurisé en ligne avec les détails de l\'article',
    'process.step1.detail2': 'Téléchargez des photos de haute qualité sous plusieurs angles',
    'process.step1.detail3': 'Incluez certificats, évaluations ou documentation de provenance',
    'process.step2.title': 'Planifier l\'expédition',
    'process.step2.description': 'Une fois approuvé, nous coordonnons l\'expédition sécurisée et assurée vers notre établissement. Votre article est protégé à chaque étape.',
    'process.step2.detail1': 'Recevez une étiquette d\'expédition prépayée et entièrement assurée',
    'process.step2.detail2': 'Directives d\'emballage professionnel fournies',
    'process.step2.detail3': 'Suivi en temps réel de la collecte à la livraison',
    'process.step3.title': 'Préparation à la vente',
    'process.step3.description': 'Notre équipe d\'experts photographie, authentifie et catalogue professionnellement votre article pour maximiser l\'intérêt et la valeur des acheteurs.',
    'process.step3.detail1': 'Photographie professionnelle dans notre studio',
    'process.step3.detail2': 'Authentification et classement par des experts',
    'process.step3.detail3': 'Description attrayante rédigée par des spécialistes',
    'process.step4.title': 'Enchères en ligne',
    'process.step4.description': 'Votre article est présenté à notre réseau mondial d\'acheteurs qualifiés. Regardez les enchères arriver et votre article trouver son nouveau propriétaire.',
    'process.step4.detail1': 'Exposition à des milliers de collectionneurs vérifiés',
    'process.step4.detail2': 'Enchères en temps réel avec mises à jour en direct',
    'process.step4.detail3': 'Support dédié tout au long de l\'enchère',
    'process.step5.title': 'Recevez votre paiement',
    'process.step5.description': 'Une fois vendu, recevez un paiement rapide et sécurisé. Notre processus transparent garantit que vous êtes payé rapidement sans frais cachés.',
    'process.step5.detail1': 'Paiement rapide dans les 7 jours ouvrables suivant la vente',
    'process.step5.detail2': 'Options de paiement multiples, y compris le virement bancaire',
    'process.step5.detail3': 'Rapport de transaction détaillé pour vos archives',
    'process.cta': 'Entrez dans les Enchères en Ligne Aujourd\'hui.',
    'process.ctaSubtext': 'Soumettez votre article de luxe et commencez votre parcours d\'enchères',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
